version: '3.8'

services:
  nginx:
    image: nginx:1.25
    ports:
      - "443:443"
    volumes:
      - ./docker/files/etc/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./certs:/etc/nginx/certs:ro
    networks:
      default:
        aliases:
          # expose proxy internally as the public names to make internal HTTPS work
          - satosa.traefik.me
          - oidc-test-client.traefik.me

  oidc-test-client:
    image: ghcr.io/beryju/oidc-test-client
    ports:
      - 9009:9009
    depends_on:
      - nginx # nginx must be up to override satosa.traefik.me resolution
      - satosa
    volumes:
      - ./certs/mkcert-root-ca.pem:/usr/local/share/ca-certificates/mkcert-root-ca.crt
    # - run update-ca-certificates to make mkcert certificates valid
    # - add startup delay because IDP must be available on boot
    entrypoint: /bin/bash -c 'update-ca-certificates && sleep 1; exec /oidc-test-client'
    environment:
      OIDC_ROOT_URL: https://oidc-test-client.traefik.me
      OIDC_PROVIDER: https://satosa.traefik.me
      OIDC_CLIENT_ID: oidc-test-client
      OIDC_CLIENT_SECRET: oidc-test-secret
      OIDC_DO_INTROSPECTION: false
      OIDC_DO_REFRESH: false
      OIDC_DO_USER_INFO: true

  satosa:
    image: satosa:8.4.0
    env_file: satosa.env
    environment:
      BASE_URL: https://satosa.traefik.me
      CLIENT_DB_JSON: |-
        {
          "oidc-test-client": {
            "response_types": [
              "id_token",
              "code"
            ],
            "redirect_uris": [
              "https://oidc-test-client.traefik.me/auth/callback"
            ],
            "client_secret": "oidc-test-secret"
          }
        }
    ports:
      - "5700:8080"
    volumes:
      - ./satosa:/etc/satosa
    entrypoint: /etc/satosa/docker-entrypoint.sh
    # this is the default command from the image, but it's reset when we override the entrypoint
    command: ["-b0.0.0.0:8080", "satosa.wsgi:app"]

